fail_fast: true
exclude: ^(docs/conf.py|frontend/)

repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.6
  hooks:
    - id: reorder-python-imports
      name: Reorder Python imports
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    #- id: check-added-large-files
    #  args: ['--maxkb=500']
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-symlinks
    - id: detect-private-key
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
- repo: git://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args: ["--line-length=120"]
    exclude: .+/(migrations)/.+

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']
